### ISSUE TITLE
Remove dependencies on py23_compat, so it works with Python 3.6

### ISSUE THREAD

**Issue by miguelhernandez-work** [napalm-automation-community/napalm-ftos#4]
Hi,
I attempted to use this library with Python 3.6.8 and its breaking on

`ImportError: cannot import name py23_compat`

My use-case is to use this with netbox.
Can we please have a version that doesn't require py23_compat?
Thanks in advance.

**Comment by skoef** [comment]
Has napalm dropped python 2 support itself? If so, the easiest fix would be to comply and drop python 2(.3) support.

I'm no python dependency expert, but perhaps if py23_compat was part of the requirements.txt file, it would automatically be installed alongside this plugin?

**Comment by miguelhernandez-work** [comment]
I was testing with this with my Dell S4048-ON switches (FTOS / Dell OS v9.x) and had to specify napalam==2.5 in my local_requirements.txt to get it to work with the raw API command,  however that then possibly caused issues with netbox not rendering the lldp results within the GUI.

**Comment by baccenfutter** [comment]
@skoef is a fix in the pipeline?
